repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  -   id: check-yaml
      exclude: doc/
  -   id: end-of-file-fixer
      exclude: doc/
  -   id: trailing-whitespace
      exclude: doc/
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  -   id: black
      exclude: doc/
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  -   id: isort
      files: hazardous/
      args: ["--profile", "black", "--filter-files"]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.270
  hooks:
    - id: ruff
